### ISSUE TITLE
Guzzle Base URI & absolute path

### ISSUE THREAD

**Issue by numerogeek** [MinotaurLogistics/EbayInventoryApi#1]
Hi @nikGkogk 

I tried to use this php client using Guzzle.
The problem is when I set up a base uri ebay.com/inventory/v1... it gets overrided because the vendor call the absolute URL /inventory_item.

Calling it that whe removes the /inventory/v1

Did you encounter this problem as well ? 

Thank you !

**Comment by nikGkogk** [comment]
Hey @numerogeek ,

I think that you don't need to pass the base url to Guzzle... just pass Guzzle to the Api classes... they already know the endpoints (thats why it overwrites what you pass probably) since they were generated from the openapi spec.

let me know if it works out ;) 👍
